runtime: nodejs10

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'strapi'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'bycovztruorE'
  INSTANCE_CONNECTION_NAME: 'spark-2-backend:europe-west4:master'

beta_settings:
  cloud_sql_instances: 'spark-2-backend:europe-west4:master'